//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APMService.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int IdOrder { get; set; }
        public int EquipmentId { get; set; }
        public string Description { get; set; }
        public int StaffId { get; set; }
        public int OrderStatusId { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
